apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-django.fullname" . }}
  labels:
    {{- include "redis-django.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "redis-django.selectorLabels" . | nindent 4 }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
