# Local backend — suitable for single-developer dev clusters.
# For CI or shared environments, migrate to a remote backend:
#
#   S3 example:
#     backend "s3" {
#       bucket         = "hackonomics-tf-state"
#       key            = "infra/terraform.tfstate"
#       region         = "us-east-1"
#       dynamodb_table = "hackonomics-tf-locks"
#       encrypt        = true
#     }
#
# To migrate: update this block, then run `terraform init -migrate-state`.
#
# SECURITY: terraform.tfstate stores plaintext DB passwords generated by
# random_password resources. Treat it as a secret — never commit it to git.
# It is listed in .gitignore.

terraform {
  backend "local" {
    path = "terraform.tfstate"
  }
}
