variable "environment" {
  type    = string
  default = "dev"
}

variable "namespace" {
  type    = string
  default = "hackonomics"
}

variable "release_name" {
  type    = string
  default = "hackonomics"
}

variable "kratos_db_password" {
  description = "Password for the Kratos-internal Postgres user. Generated by random_password in root module."
  type        = string
  sensitive   = true
}

variable "hydra_db_password" {
  description = "Password for the Hydra-internal Postgres user. Generated by random_password in root module."
  type        = string
  sensitive   = true
}

variable "hydra_enabled" {
  description = "Deploy Ory Hydra alongside Kratos."
  type        = bool
  default     = false
}
