{{- $vaultAddr := .Values.vaultAddr | default (printf "http://%s-vault.%s.svc.cluster.local:8200" .Values.releaseName .Values.namespace) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: {{ .Values.namespace }}
stringData:
  token: {{ .Values.vaultToken | quote }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: {{ .Values.namespace }}
spec:
  provider:
    vault:
      server: {{ $vaultAddr | quote }}
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
