apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres-django.fullname" . }}
  labels:
    {{- include "postgres-django.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "postgres-django.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgres-django.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres-django.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ default (include "postgres-django.fullname" .) .Values.existingSecret }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

  # Persistent volume claim template for PostgreSQL data storage (PVC in StatefulSet)
  volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: {{ .Values.storage.storageClass | quote }}
          resources:
            requests:
              storage: {{ .Values.storage.size | quote }}