"""Calendar task functions."""

import random
import uuid
from datetime import date, timedelta

from conftest import (
    CALENDAR_ME,
    CALENDAR_EVENTS,
    CALENDAR_EVENTS_CREATE,
    CALENDAR_CATEGORIES,
    CALENDAR_CATEGORY_IDS,
)


def get_my_calendar(client) -> None:
    """GET /api/calendar/me/."""
    with client.get(
        CALENDAR_ME,
        name="[calendar] get calendar",
        catch_response=True,
    ) as resp:
        if resp.status_code == 200:
            return
        resp.failure(f"calendar/me failed: {resp.status_code}")


def list_events(client) -> None:
    """GET /api/calendar/events/."""
    with client.get(
        CALENDAR_EVENTS,
        name="[calendar] list events",
        catch_response=True,
    ) as resp:
        if resp.status_code == 200:
            return
        resp.failure(f"calendar events failed: {resp.status_code}")


def create_event(client) -> None:
    """POST /api/calendar/events/create/ with a randomized future event.

    Generates a DB write; keep task weight low relative to reads.
    """
    future_date = date.today() + timedelta(days=random.randint(1, 90))
    payload = {
        "title": f"Load Test Event {uuid.uuid4().hex[:8]}",
        "event_date": future_date.isoformat(),
        "amount": round(random.uniform(100.0, 5000.0), 2),
        "category": random.choice(CALENDAR_CATEGORY_IDS),
        "note": "Generated by Locust load test",
    }
    with client.post(
        CALENDAR_EVENTS_CREATE,
        json=payload,
        name="[calendar] create event",
        catch_response=True,
    ) as resp:
        if resp.status_code in (200, 201):
            return
        resp.failure(f"create event failed: {resp.status_code} — {resp.text[:200]}")


def list_categories(client) -> None:
    """GET /api/calendar/categories/."""
    with client.get(
        CALENDAR_CATEGORIES,
        name="[calendar] categories",
        catch_response=True,
    ) as resp:
        if resp.status_code == 200:
            return
        resp.failure(f"calendar categories failed: {resp.status_code}")
