apiVersion: v1
kind: Service
metadata:
  name: {{ include "kratos.fullname" . }}
  labels:
    {{- include "kratos.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "kratos.selectorLabels" . | nindent 4 }}
  ports:
    - name: public
      port: {{ .Values.service.publicPort }}
      targetPort: public
      protocol: TCP
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
